Run clang-format in ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,6 +92,24 @@ jobs:
               exit 1
           fi
 
+  clang-format:
+    name: Clang format
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run clang-format
+        run: |
+          # Check if the code is in the correct format
+          git diff --exit-code --name-only | grep -E '\.(c|h|cpp|hpp)$' | xargs clang-format --dry-run --Werror
+          
+          # fail if the repo is dirty
+          if [ -n "$(git status --porcelain)" ]; then
+              echo "The repo is dirty. Please commit the changes."
+              exit 1
+          fi
+
   get-configs:
     name: Get Configs
     runs-on: ubuntu-latest
@@ -122,6 +140,7 @@ jobs:
       - get-configs
       - check-icons
       - check-sdkconfigs
+      - clang-format
     strategy:
       fail-fast: false
       matrix:
